### PR TITLE
added subplot grid parameters

### PR DESCRIPTION
**Pull request by shatakshipachori**

### CODE REVIEW

**Review by sreenithi — COMMENTED** [review]
Accessing subplots as integers like 221, 222, etc. does seem like an easy way if the number of rows and columns in the subplot will be fixed always as say 2x2 or 3x3. 
But as far as i understood, in our case, I think the number of rows and columns depends on the training and prediction results, so it will be better if we use the general version with (rows, columns, index) instead of the integer

@gaganmanku96 did I understand it right or are we going to have a fixed number of say 2 images only displayed for every class

**Comment by gaganmanku96** [comment]
@sreenithi I was thinking we should only display a few images from each class. Anyways the variable n_cols can be tuned to display as many images as we want from a class.

If there is a better way, can you please share some resource as well.

**Comment by sreenithi** [comment]
@gaganmanku96 There is not much of a change actually, the same add_subplot() method takes in arguments in the format of (row, column, index) instead of the 'int'. I believe @shat700 has also seen that as she had commented it in the code (I've attached the screenshot of the code snippet below). I think it's better to use this format instead of the int as it will be better for generalisation.

image

**Comment by gaganmanku96** [comment]
@sreenithi thank you.. that was helpful and the plots were dynamic as well.

@sreenithi @shat700 Can you take a quick look? After that, I'll merge the branch.

**Comment by sreenithi** [comment]
@gaganmanku96 What you've done seems good too, but I think you've still converted the number of rows, columns and index to a string to concatenate it and then again back to an int to pass it in to the add_subplot method. A more direct way of doing it will be as below:

`n_rows = len(matched_pairs)

for group, images in matched_pairs.items():
    fig = plt.figure(figsize=(10,10))
    fig.subplots_adjust(hspace=1.2)
    for idx, image in enumerate(images):
        img = plt.imread(os.path.join("images", image))
        #subplot_pos = str(n_rows) + str(idx+1) + str(idx+1)
        **ax = fig.add_subplot(n_rows, idx+1, idx+1)**
        ax.title.set_text(group)
        ax.set_xticklabels([])
        ax.set_yticklabels([])
        plt.imshow(img)`

**Comment by gaganmanku96** [comment]
@sreenithi Okay, I wasn't aware of it. I thought it had to be passed as 111.

**Pull request merged**
